env_type: irasim_wm
task_suite_name: robotwin_click_bell
wm_env_type: robotwin

total_num_envs: null

auto_reset: False
ignore_terminations: False
max_steps_per_rollout_epoch: 225
max_episode_steps: 225

use_rel_reward: True
reward_coef: 5.0

seed: 0
group_size: 1
use_fixed_reset_state_ids: True
use_ordered_reset_state_ids: False
specific_reset_id: null

video_cfg:
  save_video: True
  info_on_video: True
  chunk_keep_mode: last
  fps: 2
  video_base_dir: ${runner.logger.log_path}/video/train

enable_offload: False
print_chunk_rewards: True
success_reward_threshold: 0.9

chunk: 15
condition_frame_length: 1
num_frames: 16
image_size: [240, 320]
action_dim: 14
action_key: abs_action

task_name: click_bell
default_task_description: click the bell
irasim_root: /ML-vePFS/protected/lizhuohang/IRASim
wm_ckpt_path: /ML-vePFS/protected/lizhuohang/IRASim/results/vla_robotwin_4k_320_from_scratch/click_bell/checkpoints/0102000.pt
wm_config_path: /ML-vePFS/protected/lizhuohang/IRASim/configs/train/robotwin2/frame_ada_click_bell_4k320.yaml
vae_model_path: /ML-vePFS/protected/lizhuohang/IRASim/pretrained_models/stabilityai/stable-diffusion-xl-base-1.0
num_inference_steps: 50
guidance_scale: 1.0
train_data_dir: /ML-vePFS/protected/lizhuohang/IRASim/robotdata/vla_robotwin_4k_320_irasim/click_bell
train_data_meta: /ML-vePFS/protected/lizhuohang/IRASim/data/vla_robotwin_4k_320_click_bell_train_meta.json
val_data_meta: /ML-vePFS/protected/lizhuohang/IRASim/data/vla_robotwin_4k_320_click_bell_val_meta.json
data_mode: val
action_stat_path: /ML-vePFS/protected/lizhuohang/IRASim/robotdata/vla_robotwin_4k_320_irasim/click_bell/stat.json
enable_latent_cache: True

reward_model:
  type: RoboTwinT5CrossAttn
  from_pretrained: /manifold-obs/tangyinzhou/RLinf/diffsynth-studio/RLinf-Wan-RobotWin-ClickBell/resnet_rm.pth
  t5_model_name: /ML-vePFS/protected/tangyinzhou/RLinf/pretrained_models/t5-base
